name: Publish

env:
  NODE_VERSION: 12

on:
  release:
    types: [published]

jobs:
  dynogels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      # Log versions
      - run: npm --version; node --version
      - run: echo "PKG_VERSION=$(jq -r .version package.json)" >> $GITHUB_ENV
      # Assert release tag version matches the version we're publishing
      # NOTE: release tags **must** start with a lowercase "v" and then version
      - run: |
          if [ "v${{env.PKG_VERSION}}" != "${{ github.event.release.tag_name }}" ]; then
            echo 'Error! Package version "v${{env.PKG_VERSION}}" does not match tag version "${{ github.event.release.tag_name }}"'
            exit 1
          fi
      - run: echo 'Publishing version - ${{env.PKG_VERSION}}'
      - run: npm --version; node --version
      - run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.GH_STAMPR_PACKAGES }}" > ./.npmrc
      - run: echo "@stampr:registry=https://npm.pkg.github.com" >> ./.npmrc
      - run: npm ci
      # make sure tests pass
      - run: wget http://dynamodb-local.s3-website-us-west-2.amazonaws.com/dynamodb_local_latest.tar.gz -O /tmp/dynamodb_local_latest.tar.gz
      - run: tar -xzf /tmp/dynamodb_local_latest.tar.gz -C /tmp
      - run: java -Xmx256m -Djava.library.path=/tmp/DynamoDBLocal_lib -jar /tmp/DynamoDBLocal.jar -inMemory &
      - run: sleep 2
      - run: npm run ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GH_STAMPR_PACKAGES}}
