name: Test

on:
  push:
    # all branches
    branches:
      - '**'
    # no tags
    tags-ignore:
      - '**'

env:
  NODE_VERSION: 12

jobs:
  lib:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      # Log versions
      - run: npm --version; node --version
      - run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.GH_STAMPR_PACKAGES }}" > ./.npmrc
      - run: echo "@stampr:registry=https://npm.pkg.github.com" >> ./.npmrc
      - run: npm ci
      - run: npm run ddbinstall
      - run: npm test
